[pytest]
addopts = -p no:cacheprovider -p no:tmpdir
testpaths = tests
norecursedirs = .venv .vendor tmp .pytest_tmp tests_runtime
asyncio_mode = auto
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning:starlette\.formparsers
